FLC-328 google places support
delivero/geopy pull request #5
Opened 2016-09-09 07:23 UTC by aqueiros

2016-09-14 08:19 UTC, segv commented on geopy/geocoders/base.py
> +                    raise GeocoderTimedOut('SSLError Service timed out')
fwiw SSLErrors are almost never triggerd by a timeout, it's usually a cert mismatch or a handshake error. `SSLError connection error` would be more accurate

2016-09-14 08:20 UTC, segv commented on geopy/geocoders/googleplaces.py
> +            to 'maps.google.co.uk' to properly bias results.
have you tested this behaviour? (i know it's true for the geocoder, i'm not sure it's true for autocomplete as well)

2016-09-14 08:20 UTC, gotche commented on Makefile
> +	nosetests --verbose --nocapture --with-cover --cover-erase --cover-package=geopy test.geocoders.googlev3 test.geocoders.nominatim test.geocoders.photon test.geocoders.base test.geocoders.util test.g
what does nocapture do?

2016-09-14 08:21 UTC, segv commented on geopy/geocoders/googleplaces.py
> +            verified.
why aren't they verified?

2016-09-14 08:21 UTC, segv commented on geopy/geocoders/googleplaces.py
> +        self.details_api = '%s://%s/maps/api/place/details/json' % (self.scheme, self.domain)
let's be "modern" and use `.format`

2016-09-14 08:21 UTC, segv commented on geopy/geocoders/googleplaces.py
> +        self.doc = {}
this member seems unsued

2016-09-14 08:22 UTC, segv commented on geopy/geocoders/googleplaces.py
> +             )
unless i'm misunderstanding pyhton's `.join` method the `"|".join` will never be called because you're always passing in exactly one element

2016-09-14 08:26 UTC, gotche commented on geopy/geocoders/__init__.py
> +    "Mapzen"
don't delete the trailing comma. It is there on purpose, so adding or re arranging the tuple is easier and cleaner

2016-09-14 08:26 UTC, segv commented on geopy/geocoders/googleplaces.py
> +            self,
either 4 stops of indentation or line them up with the opening paren. 8 stops here seems random

2016-09-14 08:27 UTC, segv commented on geopy/geocoders/googleplaces.py
> +        :type offset: int
do we need to expose this in the api here? can't we move this work on to the called? (i just don't see a good usecase for this when calling the api from the backend)

2016-09-14 08:28 UTC, gotche commented on geopy/geocoders/__init__.py
> +    "googleplaces": GooglePlaces
here is another example of the trailing comma, if photon had already the trailing comma, you wouldn't have to modify that line.

2016-09-14 08:28 UTC, segv commented on geopy/geocoders/googleplaces.py
> +        :param string language: The language in which to return results.
is this an iso-639-1? or something else?

2016-09-14 08:28 UTC, segv commented on geopy/geocoders/googleplaces.py
> +            Possible values are "geocode", "address", "establishment", "(regions)" or "(cities)"
regions and cities must have parens around them?

2016-09-14 08:29 UTC, aqueiros commented on Makefile
> +	nosetests --verbose --nocapture --with-cover --cover-erase --cover-package=geopy test.geocoders.googlev3 test.geocoders.nominatim test.geocoders.photon test.geocoders.base test.geocoders.util test.g
nocapture allows print statements to be showed on the console. otherwise they are caught by nose. It was the only way I could easily debug.

2016-09-14 08:31 UTC, segv commented on geopy/geocoders/googleplaces.py
> +    def autocomplete(self, query,
put `query` on its own line

2016-09-14 08:31 UTC, segv commented on geopy/geocoders/googleplaces.py
> +        if offset:
`is not None` (if the called explicitly passes `0` or `""`, for whatever reason, you should pass that to google)

2016-09-14 08:32 UTC, segv commented on geopy/geocoders/googleplaces.py
> +        autocomplete_url = "?".join((self.autocomplete_api, urlencode(autocomplete_params)))
if find it weird to use `.join` we you always have exactly two values. do you prefer this over `"{}?{}".format(...)` ?

2016-09-14 08:34 UTC, gotche commented on test/geocoders/googleplaces.py
> +                    country = component['long_name']
indentation

2016-09-14 08:34 UTC, gotche commented on test/geocoders/googleplaces.py
> +                for type in component['types']:
indentation

2016-09-14 08:35 UTC, segv commented on test/geocoders/googleplaces.py
> +        cls.known_country_fr = "France"
let's always test something that requries encoding/utf8. france in arabic is "فرنسا"

2016-09-14 09:07 UTC, aqueiros commented on geopy/geocoders/googleplaces.py
> +        :param string language: The language in which to return results.
Adding a link according to google places documentation: https://developers.google.com/maps/faq#languagesupport

2016-09-14 09:09 UTC, aqueiros commented on geopy/geocoders/googleplaces.py
> +            Possible values are "geocode", "address", "establishment", "(regions)" or "(cities)"
Looks like it. There is an example in the [google autocomplete docs](https://developers.google.com/places/web-service/autocomplete):
`https://maps.googleapis.com/maps/api/place/autocomplete/json?input=Vict&types=(cities)&language=pt_BR&key=YOUR_API_KEY`

2016-09-14 09:23 UTC, aqueiros commented on geopy/geocoders/googleplaces.py
> +        autocomplete_url = "?".join((self.autocomplete_api, urlencode(autocomplete_params)))
I do prefer `.format`. Changing it.

2016-09-14 09:24 UTC, aqueiros commented on geopy/geocoders/googleplaces.py
> +        if offset:
I guess that applies to all the other parameters right? Changing.

2016-09-14 19:21 UTC, segv commented on geopy/geocoders/googleplaces.py
> +            autocomplete_predictions = [autocomplete_predictions[0]]
according to the documentation form geopy if `exactly_one` is true we should return a single object, not a list of length one. (this is how the googlev3 geocoder works).

it seems rather stupid to me, but that's how geopy works and unless we really want to fork it (which i don't) we should follow its api.

2016-09-14 19:24 UTC, segv commented on geopy/geocoders/googleplaces.py
> +        if autocomplete_predictions and exactly_one:
according to the documentation form geopy if exactly_one is true we should return a single object, not a list of length one. (this is how the googlev3 geocoder works).

it seems rather stupid to me, but that's how geopy works and unless we really want to fork it (which i don't) we should follow its api.

2016-09-14 19:24 UTC, segv requested changes

2016-09-15 07:58 UTC, aqueiros commented on geopy/geocoders/googleplaces.py
> +        if autocomplete_predictions and exactly_one:
Omg you are right. So for two cases where we are only returning one value, we can have either an object or a list of length=1 :O
Changing it.

2016-09-15 08:05 UTC, segv approved these changes

2016-09-15 08:21 UTC, merged